on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: c-hive/gha-remove-artifacts@v1.2.0
        with:
          age: '0 ms'
          skip-tags: false
      - uses: actions/checkout@v2.3.1
      - uses: actions/cache@v2.0.0
        with:
          path: Unity/Library
          key: Library-GrimoireForest-StandaloneWindows64
      - uses: webbertakken/unity-builder@v1.0
        with:
          unityVersion: 2019.4.1f1
          projectPath: Unity
          targetPlatform: StandaloneWindows64
      - uses: actions/upload-artifact@v2.0.1
        with:
          name: Build
          path: build
